import { type MetadataRoute } from 'next';

import { siteConfig } from '@/config/site';

/**
 * robots.txt (Sprint 01 §09, Blueprint §15).
 *
 * Allows all crawlers and points to the sitemap. Generated by the framework at
 * build so the origin is always correct.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: `${siteConfig.url}/sitemap.xml`,
    host: siteConfig.url,
  };
}
